$(document).ready(function(){

    // Get the current Date/time and put them in the header
    var currentDate = moment().format('MM-DD-YYYY'); 
    var currentHour = moment()._d.getHours();
    var currentHourInt = parseInt(currentHour);

    
    $("#currentDate").text(currentDate);

    // If our object for tracking the hours of the day and agenda per hour doesn't already exist in LocalStorage
    // We create it, if it does then we manipulate the DOM to create the content (makeCalendar function)

    if (localStorage.getItem('hoursOfDay')) {
        var existingSchedule = JSON.parse(localStorage.getItem("hoursOfDay"))
        hoursOfDay = existingSchedule
        makeCalendar()
    } else {

        var calString = JSON.stringify(hoursOfDay)
        localStorage.setItem("hoursOfDay", calString)
        var existingSchedule = JSON.parse(localStorage.getItem("hoursOfDay"))
        hoursOfDay = existingSchedule

        makeCalendar()

    }

    function makeCalendar() {

    // For loop to create an entry for every hour object in the hoursOfDay array, we also declare the time variables
    // that will be used to determine how each time block is color-coated

    for (var i = 0; i < hoursOfDay.length; i ++) {

        var hourDisplay = hoursOfDay[i].hour
        var whatHour = hoursOfDay[i].mil;
        var agendaDisplay = hoursOfDay[i].agenda
        var whatHourInt = parseInt(whatHour);
        // Button and input name attributes to determine what button ties to what input field
        var nameElBtn = "button-name" + i
        var nameElIn = "input-name" + i
        // Creating LI, Input, Button, and Span Elements
        var newLI = $('<li>')
        var newInput = $('<input type="text"/>');
        var newSpan = $('<span>')
        var saveBtn = $('<button class="app-button">')
        // Turn our hourDisplay variable into a variable that can be understoor by moment.js
        var momentHours = moment(hourDisplay, "h:mmA")
        var momentHourCurrent = moment(momentHours, 'h')
        // conditionals for whether the current time is after a given hour on the schedule
        var checkTime = moment().isAfter(momentHours)

    
        // Add an input field and fill the text content with the corresponding field from localStorage
        // We also assign a "name" attribute based on the variable for determining this
        $(newInput).attr("value", agendaDisplay);
        $(newInput).attr("name", nameElIn);
        // Each Span will have a different hour displayed
        $(newSpan).text(hourDisplay)
        // An <li> to the <ul>, and add the span, buttons, and input fields to that <li>
        $("#base-ul").append(newLI);
        $(newLI).prepend(newSpan)
        $(newLI).append(newInput);

        // If the current hour matches the hour of a given time block
        // We turn the background light blue

        if (currentHourInt == whatHourInt){
            $(newInput).removeClass("future");
            $(newInput).removeClass("past");
            $(newInput).addClass("present");
        }
        else if (currentHourInt > whatHourInt) {
            // If that hour has passed,
            // We turn the input field background red
            $(newInput).removeClass("future");
            $(newInput).addClass("past");
            $(newInput).removeClass("present");
        } else {
            // If that time hasn't passed, we turn it grey
            $(newInput).addClass("future");
            $(newInput).removeClass("past");
            $(newInput).removeClass("present");
        }
        // Add the save button, its name attribute, and append it to the LI
        $(saveBtn).text("Save");
        $(saveBtn).attr("name", nameElBtn);
        $(newLI).append(saveBtn);
        
    }

    // When any of the save buttons are clicked...
    $(".app-button").on("click", function(event) {

        event.preventDefault();

        // We assign a unique name attribute generated by our for loop to the button
        var btnName = ($(this).attr("name"));
        // Grab the number from the end of that name
        var inputNumber = btnName.slice(-1);
        // and append it to the input name to tie that button to its respective input field
        var inputName = "input-name" + inputNumber
        var inputToString = inputName.toString();
        var inputFinal = document.getElementsByName(inputToString);
        var inputInteger = parseInt(inputNumber);

        // This for loop is for gathering the content typed into the input field, turning it into a string, and pushing it to localStorage

        for (var i = 0; i < inputFinal.length; i++) {
            var textValue = inputFinal[i].value;
            
            hoursOfDay[inputInteger].agenda = textValue;
            var calString = JSON.stringify(hoursOfDay)
            localStorage.setItem("hoursOfDay", calString)

            
        
        }

    })

    }

})